# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
test:
  machine:
    enabled: true
  steps:
    - run: echo "Tests can run here!"
deploy:
  machine:
    enabled: true
  steps:
    - run:
        name: Install NodeJS & NPM
        command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install curl && curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs"
    - run:
        name: Clone Repo & Install Application Dependencies
        command: ssh $SSH_USER@$SSH_HOST "git clone https://gitlab.com/qacdevops/pokedex-example && cd ~/pokedex-example && npm install"
    - run:
        name: Deploy Application
        command: ssh $SSH_USER@$SSH_HOST "cd ~/pokedex-example && npm run serve"
workflows:
version: 2.1
test-and-deploy:
  jobs:
    - test
    - deploy:
        requires:
          - test
